### ISSUE TITLE
Creating a new project as a contributer giving 403 but still creating project

### ISSUE THREAD

**Issue by cburch-bb** [stoplightio/desktop#259] opened 2018-07-10 16:49 UTC
As the title says, my permission level was Contributor, I tried to create a new project and after typing in the name and clicking create I received a 403 error.  Back out on the project page a project existed with the name I was using but is completely empty.

**Comment by rossmcdonald** [comment] 2018-07-10 16:55
Hi @cburch-bb, thanks for opening this issue. We are aware of the problem and are currently working  on a fix. As a short-term workaround, any Contributor users needing to create projects can have their privileges upgraded to Administrator until the issue is resolved.

I'll comment on this issue once the fix is live.

**Comment by rossmcdonald** [comment] 2018-07-11 15:00
The fix for this issue is now live.

**Closed by rossmcdonald** 2018-07-11 15:00 UTC
