### ISSUE TITLE
Non standard alternative types

### ISSUE THREAD

**Issue by ozum** [stoplightio/desktop#312] opened 2018-09-10 08:26 UTC
Hi,

When I choose more than one alternative data types, Stoplight produces an array of data types:

```json
"type": ["string", "number"]
```

![image](https://user-images.githubusercontent.com/1497060/45285388-bc0bbc00-b4eb-11e8-874a-cd8f9206523a.png)
![image](https://user-images.githubusercontent.com/1497060/45285404-c5952400-b4eb-11e8-9e1d-0bca1529fd3f.png)

According to OpenAPI spec, it is wrong. Please see [Mixed Types section in OpenAPI doc](https://swagger.io/docs/specification/data-models/data-types/)

Kind Regards,

**Comment by tbarn** [comment] 2018-11-13 18:54
I'm going to close since this is a duplicate of #51. We'll be working to address this there.

**Closed by tbarn** 2018-11-13 18:54 UTC
Labels: Next, duplicate
