### ISSUE TITLE
Markdown editor should fill height for easier clicking

### ISSUE THREAD

**Issue by pytlesk4** [stoplightio/desktop#118] opened 2018-01-05 18:17 UTC
When I click in the editor I would expect the cursor to show up.

![weirdcursor.gif](https://codetreeusercontent.s3.amazonaws.com/uploads/895d640e-e8b4-4bf0-b384-6c94f425fb8f/weirdcursor.gif)

**Comment by casserni** [comment] 2018-01-12 23:46
duplicate of https://codetree.com/projects/WFjL/issues/5605026?assignee=casserni

**Comment by lottamus** [comment] 2018-01-13 01:02
Duplicate of #122

**Closed by lottamus** 2018-01-13 01:02 UTC
Labels: done, enhancement
